### ISSUE TITLE
crashes dedicated Forge 1.8 b1334

### ISSUE THREAD

**Issue by kreezxil** [sidben/VillagerTweaks#18]
crashes dedicated Forge 1.8 b1334 server while looking for missing method 'sidben.villagertweaks.init.MyItems.registerRender' among other things
Crash Report: http://pastebin.com/8Ub8hKQd
FML Server Latest: http://pastebin.com/Fijby53t

**Comment by kreezxil** [comment]
client side works fine

**Comment by sidben** [comment]
Thanks, I'll check the server build on my dev machine, should be easy to fix.

**Comment by kreezxil** [comment]
Cool. :)

**Comment by sidben** [comment]
Hey @kreezxil, I just uploaded a fix for this issue, could you try it out and let me know if it worked?

Here is a MediaFire link: http://www.mediafire.com/download/n2b5xlfffzr49lt/VillagerTweaks[1.8]-2.1.jar

Thanks!

**Comment by kreezxil** [comment]
Excellent, just tried it and the client and server booted fine, and the
client connected to the server fine. So at least that part works. If detect
more bugs during my let's plays I'll report them as well.

**Comment by sidben** [comment]
Ok, closing I'm closing this issue as "fixed", many thanks.
